### ISSUE TITLE
Flaky test: test.ajax.js-http #5061 ajax returns ETIMEDOUT error on timeout:

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/pouchdb-adapter-fs#46]
seen it on travis and locally, tested with Node v6 and v7

```
  1) test.ajax.js-http #5061 ajax returns ETIMEDOUT error on timeout:

     Uncaught AssertionError: expected 'ESOCKETTIMEDOUT' to match /(ETIMEDOUT|ENETUNREACH|EAGAIN|ECONNREFUSED)/
      at tests/integration/test.ajax.js:19:25
      at Request._callback (node_modules/pouchdb-ajax/lib/index.js:79:14)
      at self.callback (node_modules/request/request.js:187:22)
      at ClientRequest.<anonymous> (node_modules/request/request.js:779:16)
      at Socket.socket.once (_http_client.js:566:38)
      at Socket._onTimeout (net.js:339:8)
```

**Comment by nolanlawson** [comment]
We have updated the tests in PouchDB's codebase to include `ESOCKETTIMEDOUT`. Unfortunately this is one of the problems with copy-pasta'ing the tests.
